# Generated by Django 5.1.2 on 2024-10-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inventory",
            old_name="change_type",
            new_name="status",
        ),
        migrations.AddField(
            model_name="inventory",
            name="batch_id",
            field=models.CharField(
                editable=False, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="inventory",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="batch_id",
            field=models.CharField(
                blank=True, editable=False, max_length=100, unique=True
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("product", "created_at", "expiry_date")},
        ),
    ]
