# Generated by Django 5.1.2 on 2024-10-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_shipment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
