# Generated by Django 5.1.2 on 2024-11-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_notification_alter_purchaseorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
