# Generated by Django 5.1.2 on 2024-11-19 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_notification_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="batch_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="api.inventory",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="product_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="api.product",
            ),
        ),
    ]
