# Generated by Django 5.1.2 on 2024-11-20 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_notification_batch_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="batch_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="api.inventory",
            ),
        ),
    ]
